# This is a basic workflow to help you get started with Actions

name: Fortify ScanCentral SAST Scan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SAST"
  Fortify-SAST:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Source Code
        uses:  actions/checkout@v2
        with: 
          # Fetch at least the immediate parents so that if this is a pull request then we can checkout the head.
          fetch-depth: 2
          # If this run was triggered by a pull request event, then checkout the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
        
#      - name: setup Java for Fortify
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
      
 #     - name: download Fortify Scan central
 #       uses: fortify/gha-setup-scancentral-client@v1.1.0
 #       with:
 #         version: 20.1.0
 #         client-auth-token: ${{ secrets.CLIENT_AUTH_TOKEN }}
          
      # Runs a single command using the runners shell
      - name: Get Envionrment Variables
        run: |
          echo $home
          echo ${{ github.workspace }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 'Add other actions to build,'
          echo 'test, and deploy your project.'

      ### Run Fortify ScanCentral Client ###
      # Update BUILD_OPTS based on the ScanCentral Client documentation and your project's included tech stack(s).
      #   ScanCentral Client will download dependencies for maven, gradle and msbuild projects.
      #   For other build tools, add your build commands to the workflow to download necessary dependencies and prepare according to Fortify SCA documentation.
      - name: Perform SAST Scan
        run: | 
          sourceanalyzer -b juice-shop -clean
          sourceanalyzer -b juice-shop -debug-verbose -logfile gh-rohit.log "${{ github.workspace }}\**\*"
          #scancentral -url ${URL} start $BUILD_OPTS -upload -application $APPLICATION --application-version $VERSION -b juice-shop -uptoken $TOKEN -scan -Xmx2G
          scancentral -url "http://fortify201.myhome.com:8280/scancentral-ctrl" start -upload -application "github-juice-shop" --application-version "0.1" -b sec-demo -uptoken bda951b8-9425-414d-a84f-35931a7e86cc -scan -Xmx2G
        env:                                            
          URL: http://fortify201.myhome.com:8280/scancentral-ctrl
          TOKEN: bda951b8-9425-414d-a84f-35931a7e86cc
          APPLICATION: "github-juice-shop"
          VERSION: "0.1"
          BUILD_OPTS: ""         
      
      ### Archive ScanCentral Client logs on failure ###
    #  - name: Save ScanCentral Logs
    #  - uses: actions/upload-artifact@v2                
    #    if: failure()
    #    with:
    #       name: scancentral-logs
    #       path: ~/.fortify/scancentral/log
